require "test_helper"

class Document::BodyTest < ActiveSupport::TestCase
  # Generated by tiptap-provenance/scripts/contract_fixture.js from the
  # editor's own schema and toStandoff: server and editor must agree on
  # every block, position and offset, or the indexes point at the wrong text.
  test "blocks match the editor's stand-off export" do
    JSON.parse(file_fixture("standoff_contract.json").read).each do |name, contract|
      blocks = Document::Body.new(contract["body"]).blocks.map { |block| block.to_h.except(:index).deep_stringify_keys.merge("marks" => block.marks.map { |mark| mark.to_h.deep_stringify_keys }) }

      assert_equal contract["standoff"], blocks, "stand-off mismatch for #{name}"
    end
  end

  test "offsets are UTF-16 units, like the editor's" do
    body = Document::Body.new(JSON.parse(file_fixture("standoff_contract.json").read).dig("astral_characters", "body"))
    human = body.blocks.first.marks.find { |mark| mark.attrs["origin"] == "human" }

    assert_equal "🙏", Document::Body.utf16_slice(body.blocks.first.text, human.start, human.end)
  end

  test "rejects unknown nodes, marks and attrs, unsafe links and bad citations" do
    body = Document::Body.new(type: "doc", content: [
      { type: "script", content: [] },
      { type: "paragraph", attrs: { onclick: "x" }, content: [
        { type: "text", text: "a", marks: [ { type: "link", attrs: { href: "javascript:alert(1)" } } ] },
        { type: "text", text: "b", marks: [ { type: "provenance", attrs: { origin: "magic" } } ] },
        { type: "text", text: "c", marks: [ { type: "bibleRef", attrs: { osis: "Nope.1.1" } } ] },
        { type: "text", text: "d", marks: [ { type: "comment" } ] }
      ] }
    ])

    assert_equal [
      %(unknown node type "script"),
      "paragraph has unknown attrs onclick",
      %(unsafe link "javascript:alert(1)"),
      %(unknown provenance origin "magic"),
      %(invalid citation "Nope.1.1"),
      %(unknown mark type "comment")
    ], body.errors
  end
end
